# requiring the environment of NodeJS 10
image: node:20

# add 'node_modules' to cache for speeding up builds
cache:
  paths:
    - node_modules/ # Node modules and dependencies

# the 'pages' job will deploy and build your site to the 'build' path
pages:
  tags:
    - Pages
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public

  artifacts:
    paths:
      - public
  only:
    - main # this job will affect only the 'master' branch

